### ISSUE TITLE
Motiga Module

### ISSUE THREAD

**Issue by indierespawn** [patcorwin/fossil#1]
Hey I threw the scripts in the maya 2018 scripts folder in My Documents, this is the error i get run i try to initialize the following command:

import pdil.tool.fossil.main
pdil.tool.fossil.main.RigTool()

# Error: ImportError: file C:/Users/alanz/Documents/maya/2018/scripts\pdil\tool\fossil\ui\rigToolUI.py line 362: No module named motiga.tool.fossil.cardlister # 

Im not sure what to do and I really want to play with this tool set! Thanks!

**Comment by patcorwin** [comment]
Thanks for reporting this!  I just uploaded the fix so it should work fine now.  Let me know if you run into any other issues.
