### ISSUE TITLE
Hip Card has errors when building Dogleg module

### ISSUE THREAD

**Issue by BenFreedman** [patcorwin/fossil#10]
/                                                                                                                             \
| Hip_card                                                                                                                    |
| Traceback (most recent call last):                                                                                          |
|   File "C:/Users/ben.freedman/Documents/maya/2019/scripts\pdil\tool\fossil\cardRigging.py", line 816, in buildRig           |
|     registeredControls[ card.rigData.get('rigCmd') ].build(card)                                                            |
|   File "C:/Users/ben.freedman/Documents/maya/2019/scripts\pdil\tool\fossil\cardRigging.py", line 598, in build              |
|     ctrls = cls._buildSide(card, card.start().real, card.end().real, False, side, buildFk=buildFk)                          |
|   File "C:/Users/ben.freedman/Documents/maya/2019/scripts\pdil\tool\fossil\cardRigging.py", line 537, in _buildSide         |
|     name, ikCtrl, ikConstraints = cls._buildIk(card, start, end, side, sideAlteration, isMirroredSide)                      |
|   File "C:/Users/ben.freedman/Documents/maya/2019/scripts\pdil\tool\fossil\cardRigging.py", line 567, in _buildIk           |
|     ikCtrl, ikConstraints = cls.ik( start, end, groupName=ikGroupName, **kwargs )                                           |
|   File "C:/Users/ben.freedman/Documents/maya/2019/scripts\pdil\tool\fossil\rigging\_util.py", line 118, in newFunc          |
|     res = func(*args, **kwargs)                                                                                             |
|   File "C:/Users/ben.freedman/Documents/maya/2019/scripts\pdil\tool\fossil\rigging\dogHindLeg.py", line 213, in buildDogleg |
|     util.makeStretchyNonSpline(footCtrl, mainIk)                                                                            |
| AttributeError: 'module' object has no attribute 'makeStretchyNonSpline'                                                    |
\_____________________________________________________________________________________________________________________________/
 _________________________________
/                                 \
| The following cards had errors: |
| Hip_card                        |

-It's worth noting that this happens even when I don't modify anything in the dogleg template build.
-This happened in 2019

**Comment by BenFreedman** [comment]
Was able to actually get the doglegs to build, albeit with errors by commenting out line 213 "util.makeStretchyNonSpline(footCtrl, mainIk)"

**Comment by patcorwin** [comment]
This got fixed at some point in the past, forgot to close it out then.
