### ISSUE TITLE
Mirrored joints are created and improper scale when units are not cm

### ISSUE THREAD

**Issue by kungfoojoh** [patcorwin/fossil#11]
If I set the units in maya prefs to inches meters or anything other than cm. mirrored joints e.g. the leg_r  joints are created really big.

**Comment by kungfoojoh** [comment]
Also wanted to add that the Dog Leg ctrls don't build properly when units are not cm aswell

**Comment by patcorwin** [comment]
Fixed, dogleg building wrong moved to a new issue.
