### ISSUE TITLE
Fossil Window has lower priority than other windows in Maya.

### ISSUE THREAD

**Issue by kungfoojoh** [patcorwin/fossil#17]
It keeps getting covered up by outliner, attrib editor, Hypershade, and even Maya itself

**Comment by kungfoojoh** [comment]
adding this in main.py fix this issue:

self.setWindowFlags(Qt.QtCore.Qt.Tool)

**Comment by patcorwin** [comment]
I added this line.  It does nothing for me on windows but hopefully it works for you.
