### ISSUE TITLE
Ability to customize how left and right are named

### ISSUE THREAD

**Issue by kungfoojoh** [patcorwin/fossil#19]
It would nice to have the ability to customize how left and right are named.

some options would be: 
- what the text sensitive case is (eg. leg_l, or leg_left, leg_L, leg_Left)
- whether it's at the beginning or end of the name (eg. R_Leg , Leg_R)

.. and to have ctrls named to match (eg. R_Leg_ctrl , Leg_right_ctrl)

**Comment by patcorwin** [comment]
I'm closing this since the main issue is now configurable under Settings -> Naming Rules.  We can talk about the ordering separately if you want.
