### ISSUE TITLE
Support For Old Rigs?

### ISSUE THREAD

**Issue by kowdow** [patcorwin/fossil#22]
Hey Pat! I was just thinking of tinkering around with an old Gigantic rig. I opened in up in Maya 2019 and found that the cards were being recognized in the Fossil UI list. Also I don't see the spaces or FK/IK in the DAG right-click menu. When I create a new rig, neither of these issues occur.

Is this expected at this point? If so, I'm wondering if there's a smart way I could bring the old rigs up to date with the tools.

**Comment by patcorwin** [comment]
FWIW, I haven't made supporting the really old stuff a priority at all.  There is a little code I have for updating, and I tried it but there have been a lot of updates.  I could probably get the card build data mostly updated so the rig could be rebuilt, though there still might be some manual work, and possilby some components don't work the same way anymore.

I was hoping it would be trivial to rebuild an old rig, but after an hour of experimenting, I'm still hitting some issues so it's impossible to know if there is just bit more work or this is wild goose chase without just going farther.

**Comment by kowdow** [comment]
Bummer! I might try a manual rebuild. It's one of the more complex rigs so it might not be worth for my little project.

Thanks for digging into it Pat. :D
