### ISSUE TITLE
Storing modified default spaces is not restoring as expected

### ISSUE THREAD

**Issue by kungfoojoh** [patcorwin/fossil#23]
Certain components build default spaces (splineTwist will create local,main, parent)

If we end up deleting these, or renaming them. They restore back to default. The default spaces that were deleted are recreated on restore. and the ones that we're renamed restore with the original name.

This happens on the SplineTwist, SplineNeck, IK, dogIK

it would be great if restoring the mods restored the spaces exactly as they we're stored

**Comment by patcorwin** [comment]
Typo in rebuild.py now fixed.
