### ISSUE TITLE
No module named PySide2

### ISSUE THREAD

**Issue by alelekita** [patcorwin/fossil#3]
Heheh, sorry Pat, now I got this error:

C:/Users/Alessandra/Documents/maya/scripts\pdil\tool\fossil\ui\rigToolUI.py line 10: No module named PySide2

**Comment by patcorwin** [comment]
My apologies.  I sometimes forget to test in older versions of Maya as 2017 switched to PySide2.  I tested in 2016 and it works.

**Comment by alelekita** [comment]
It worked!! 👍
