### ISSUE TITLE
unable to build Spline Neck module

### ISSUE THREAD

**Issue by andrionbecker** [patcorwin/fossil#6]
Fossil keeps giving me errors when I try to build the spline neck module. It does build something, but I'm not sure if it's working as designed or not
/                                                                                                                        \
| card_card                                                                                                              |
| Traceback (most recent call last):                                                                                     |
|   File "C:/Users/Archanex/Documents/maya/scripts\pdil\tool\fossil\cardRigging.py", line 816, in buildRig               |
|     registeredControls[ card.rigData.get('rigCmd') ].build(card)                                                       |
|   File "C:/Users/Archanex/Documents/maya/scripts\pdil\tool\fossil\cardRigging.py", line 589, in build                  |
|     ctrls = cls._buildSide(card, card.start().real, card.end().real, False, buildFk=buildFk)                           |
|   File "C:/Users/Archanex/Documents/maya/scripts\pdil\tool\fossil\cardRigging.py", line 537, in _buildSide             |
|     name, ikCtrl, ikConstraints = cls._buildIk(card, start, end, side, sideAlteration, isMirroredSide)                 |
|   File "C:/Users/Archanex/Documents/maya/scripts\pdil\tool\fossil\cardRigging.py", line 567, in _buildIk               |
|     ikCtrl, ikConstraints = cls.ik( start, end, groupName=ikGroupName, **kwargs )                                      |
|   File "C:/Users/Archanex/Documents/maya/scripts\pdil\tool\fossil\rigging\_util.py", line 118, in newFunc              |
|     res = func(*args, **kwargs)                                                                                        |
|   File "C:/Users/Archanex/Documents/maya/scripts\pdil\tool\fossil\rigging\splineNeck.py", line 208, in buildSplineNeck |
|     util.driveConstraints( constraints, endConstraints )                                                               |
| AttributeError: 'module' object has no attribute 'driveConstraints'                                                    |
\________________________________________________________________________________________________________________________/
 _________________________________
/                                 \
| The following cards had errors: |
| card_card                       |
\_________________________________/

**Comment by patcorwin** [comment]
Thanks for the report, definitely not how it's supposed to work but is now fixed in the latest.
