### ISSUE TITLE
Running RigTool in 2016 gave me an error

### ISSUE THREAD

**Issue by BenFreedman** [patcorwin/fossil#8]
import pdil.tool.fossil.main
pdil.tool.fossil.main.RigTool()

# Traceback (most recent call last):
#   File "C:/MAYA_APP_DIR/2016/scripts\pdil\tool\fossil\main.py", line 296, in closeEvent
#     self.shapeEditor.curveColorLayout.setObjectName( 'delete_me3' )
# AttributeError: 'RigTool' object has no attribute 'shapeEditor'
# Error: AttributeError: file C:/MAYA_APP_DIR/2016/scripts\pdil\tool\fossil\cardlister.py line 279: 'PySide.QtGui.QHeaderView' object has no attribute 'setSectionResizeMode' #

**Comment by patcorwin** [comment]
It looks like you're not running the latest because that isn't the right line number.  The easiest/safest thing to do is to completely delete the existing pdil folder, download it fresh and reinstall it

**Comment by BenFreedman** [comment]
Indeed, user error.  Thanks Pat!
